services:
  # Web Service (Backend + Frontend)
  - type: web
    name: pokemon-mern-app
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: pokemon-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://pokemon-mern-app.onrender.com
      - key: POKEMON_API_BASE_URL
        value: https://pokeapi.co/api/v2

databases:
  # MongoDB Database
  - name: pokemon-db
    plan: free
